/**
 * AUTO-GENERATED Android audio stubs — all methods are no-ops.
 * Generated by parsing include/audio/*.hpp for non-inline method declarations.
 */

#include "audio/activity_sound_manager.hpp"
#include "audio/ambient_sound_manager.hpp"
#include "audio/audio_coordinator.hpp"
#include "audio/combat_sound_manager.hpp"
#include "audio/footstep_manager.hpp"
#include "audio/mount_sound_manager.hpp"
#include "audio/movement_sound_manager.hpp"
#include "audio/music_manager.hpp"
#include "audio/npc_voice_manager.hpp"
#include "audio/player_voice_manager.hpp"
#include "audio/spell_sound_manager.hpp"
#include "audio/ui_sound_manager.hpp"
#include "game/zone_manager.hpp"
#include "pipeline/asset_manager.hpp"
#include <cstdint>
#include <glm/glm.hpp>
#include <memory>
#include <string>
#include <vector>

namespace wowee::audio {

// --- AssetManager ---
public: AssetManager::ActivitySoundManager() { return {}; }
bool AssetManager::initialize(pipeline::AssetManager* assets) { return false; }
void AssetManager::shutdown() {}
void AssetManager::update(float deltaTime) {}
void AssetManager::playJump() {}
void AssetManager::playLanding(FootstepSurface surface, bool hardLanding) {}
void AssetManager::setSwimmingState(bool swimming, bool moving) {}
void AssetManager::setCharacterVoiceProfile(const std::string& modelName) {}
void AssetManager::setCharacterVoiceProfile(const std::string& raceFolder, const std::string& raceBase, bool male) {}
void AssetManager::playWaterEnter() {}
void AssetManager::playWaterExit() {}
void AssetManager::playMeleeSwing() {}
void AssetManager::playAttackGrunt() {}
void AssetManager::playWound(bool isCrit = false) {}
void AssetManager::playDeath() {}
void AssetManager::preloadCandidates(std::vector<Sample>& out, const std::vector<std::string>& candidates) {}
void AssetManager::preloadLandingSet(FootstepSurface surface, const std::string& material) {}
void AssetManager::rebuildJumpClipsForProfile(const std::string& raceFolder, const std::string& raceBase, bool male) {}
void AssetManager::rebuildSwimLoopClipsForProfile(const std::string& raceFolder, const std::string& raceBase, bool male) {}
void AssetManager::rebuildHardLandClipsForProfile(const std::string& raceFolder, const std::string& raceBase, bool male) {}
void AssetManager::rebuildCombatVocalClipsForProfile(const std::string& raceFolder, const std::string& raceBase, bool male) {}
bool AssetManager::playSplash(const std::vector<Sample>& clips) { return false; }
void AssetManager::startSwimLoop() {}
void AssetManager::stopSwimLoop() {}
void AssetManager::stopOneShot() {}
void AssetManager::reapProcesses() {}
// --- ActivitySoundManager ---
bool ActivitySoundManager::initialize(pipeline::AssetManager* assets) { return false; }
void ActivitySoundManager::shutdown() {}
void ActivitySoundManager::update(float deltaTime) {}
void ActivitySoundManager::playJump() {}
void ActivitySoundManager::playLanding(FootstepSurface surface, bool hardLanding) {}
void ActivitySoundManager::setSwimmingState(bool swimming, bool moving) {}
void ActivitySoundManager::setCharacterVoiceProfile(const std::string& modelName) {}
void ActivitySoundManager::setCharacterVoiceProfile(const std::string& raceFolder, const std::string& raceBase, bool male) {}
void ActivitySoundManager::playWaterEnter() {}
void ActivitySoundManager::playWaterExit() {}
void ActivitySoundManager::playMeleeSwing() {}
void ActivitySoundManager::playAttackGrunt() {}
void ActivitySoundManager::playWound(bool isCrit = false) {}
void ActivitySoundManager::playDeath() {}
void ActivitySoundManager::preloadCandidates(std::vector<Sample>& out, const std::vector<std::string>& candidates) {}
void ActivitySoundManager::preloadLandingSet(FootstepSurface surface, const std::string& material) {}
void ActivitySoundManager::rebuildJumpClipsForProfile(const std::string& raceFolder, const std::string& raceBase, bool male) {}
void ActivitySoundManager::rebuildSwimLoopClipsForProfile(const std::string& raceFolder, const std::string& raceBase, bool male) {}
void ActivitySoundManager::rebuildHardLandClipsForProfile(const std::string& raceFolder, const std::string& raceBase, bool male) {}
void ActivitySoundManager::rebuildCombatVocalClipsForProfile(const std::string& raceFolder, const std::string& raceBase, bool male) {}
bool ActivitySoundManager::playSplash(const std::vector<Sample>& clips) { return false; }
void ActivitySoundManager::startSwimLoop() {}
void ActivitySoundManager::stopSwimLoop() {}
void ActivitySoundManager::stopOneShot() {}
void ActivitySoundManager::reapProcesses() {}
// --- AssetManager ---
void AssetManager::update(float deltaTime, const glm::vec3& cameraPos, bool isIndoor, bool isSwimming = false, bool isBlacksmith = false) {}
void AssetManager::setWeather(WeatherType type) {}
void AssetManager::setZoneType(ZoneType type) {}
void AssetManager::setZoneId(uint32_t zoneId) {}
void AssetManager::setCityType(CityType type) {}
uint64_t AssetManager::addEmitter(const glm::vec3& position, AmbientType type) { return 0; }
void AssetManager::removeEmitter(uint64_t id) {}
void AssetManager::clearEmitters() {}
void AssetManager::setGameTime(float hours) {}
void AssetManager::setVolumeScale(float scale) {}
void AssetManager::updatePositionalEmitters(float deltaTime, const glm::vec3& cameraPos) {}
void AssetManager::updatePeriodicSounds(float deltaTime, bool isIndoor, bool isSwimming) {}
void AssetManager::updateWindAmbience(float deltaTime, bool isIndoor) {}
void AssetManager::updateBlacksmithAmbience(float deltaTime) {}
void AssetManager::updateWeatherAmbience(float deltaTime, bool isIndoor) {}
void AssetManager::updateWaterAmbience(float deltaTime, bool isSwimming) {}
void AssetManager::updateZoneAmbience(float deltaTime, bool isIndoor) {}
void AssetManager::updateCityAmbience(float deltaTime) {}
void AssetManager::updateBellTolls(float deltaTime) {}
bool AssetManager::loadSound(const std::string& path, AmbientSample& sample, pipeline::AssetManager* assets) { return false; }
// --- AmbientSoundManager ---
bool AmbientSoundManager::initialize(pipeline::AssetManager* assets) { return false; }
void AmbientSoundManager::shutdown() {}
void AmbientSoundManager::update(float deltaTime, const glm::vec3& cameraPos, bool isIndoor, bool isSwimming = false, bool isBlacksmith = false) {}
void AmbientSoundManager::setWeather(WeatherType type) {}
void AmbientSoundManager::setZoneType(ZoneType type) {}
void AmbientSoundManager::setZoneId(uint32_t zoneId) {}
void AmbientSoundManager::setCityType(CityType type) {}
uint64_t AmbientSoundManager::addEmitter(const glm::vec3& position, AmbientType type) { return 0; }
void AmbientSoundManager::removeEmitter(uint64_t id) {}
void AmbientSoundManager::clearEmitters() {}
void AmbientSoundManager::setGameTime(float hours) {}
void AmbientSoundManager::setVolumeScale(float scale) {}
void AmbientSoundManager::updatePositionalEmitters(float deltaTime, const glm::vec3& cameraPos) {}
void AmbientSoundManager::updatePeriodicSounds(float deltaTime, bool isIndoor, bool isSwimming) {}
void AmbientSoundManager::updateWindAmbience(float deltaTime, bool isIndoor) {}
void AmbientSoundManager::updateBlacksmithAmbience(float deltaTime) {}
void AmbientSoundManager::updateWeatherAmbience(float deltaTime, bool isIndoor) {}
void AmbientSoundManager::updateWaterAmbience(float deltaTime, bool isSwimming) {}
void AmbientSoundManager::updateZoneAmbience(float deltaTime, bool isIndoor) {}
void AmbientSoundManager::updateCityAmbience(float deltaTime) {}
void AmbientSoundManager::updateBellTolls(float deltaTime) {}
bool AmbientSoundManager::loadSound(const std::string& path, AmbientSample& sample, pipeline::AssetManager* assets) { return false; }
// --- WeatherType ---
bool WeatherType::initialize(pipeline::AssetManager* assets) { return false; }
void WeatherType::shutdown() {}
void WeatherType::update(float deltaTime, const glm::vec3& cameraPos, bool isIndoor, bool isSwimming = false, bool isBlacksmith = false) {}
void WeatherType::setWeather(WeatherType type) {}
void WeatherType::setZoneType(ZoneType type) {}
void WeatherType::setZoneId(uint32_t zoneId) {}
void WeatherType::setCityType(CityType type) {}
uint64_t WeatherType::addEmitter(const glm::vec3& position, AmbientType type) { return 0; }
void WeatherType::removeEmitter(uint64_t id) {}
void WeatherType::clearEmitters() {}
void WeatherType::setGameTime(float hours) {}
void WeatherType::setVolumeScale(float scale) {}
void WeatherType::updatePositionalEmitters(float deltaTime, const glm::vec3& cameraPos) {}
void WeatherType::updatePeriodicSounds(float deltaTime, bool isIndoor, bool isSwimming) {}
void WeatherType::updateWindAmbience(float deltaTime, bool isIndoor) {}
void WeatherType::updateBlacksmithAmbience(float deltaTime) {}
void WeatherType::updateWeatherAmbience(float deltaTime, bool isIndoor) {}
void WeatherType::updateWaterAmbience(float deltaTime, bool isSwimming) {}
void WeatherType::updateZoneAmbience(float deltaTime, bool isIndoor) {}
void WeatherType::updateCityAmbience(float deltaTime) {}
void WeatherType::updateBellTolls(float deltaTime) {}
bool WeatherType::loadSound(const std::string& path, AmbientSample& sample, pipeline::AssetManager* assets) { return false; }
// --- ZoneType ---
bool ZoneType::initialize(pipeline::AssetManager* assets) { return false; }
void ZoneType::shutdown() {}
void ZoneType::update(float deltaTime, const glm::vec3& cameraPos, bool isIndoor, bool isSwimming = false, bool isBlacksmith = false) {}
void ZoneType::setWeather(WeatherType type) {}
void ZoneType::setZoneType(ZoneType type) {}
void ZoneType::setZoneId(uint32_t zoneId) {}
void ZoneType::setCityType(CityType type) {}
uint64_t ZoneType::addEmitter(const glm::vec3& position, AmbientType type) { return 0; }
void ZoneType::removeEmitter(uint64_t id) {}
void ZoneType::clearEmitters() {}
void ZoneType::setGameTime(float hours) {}
void ZoneType::setVolumeScale(float scale) {}
void ZoneType::updatePositionalEmitters(float deltaTime, const glm::vec3& cameraPos) {}
void ZoneType::updatePeriodicSounds(float deltaTime, bool isIndoor, bool isSwimming) {}
void ZoneType::updateWindAmbience(float deltaTime, bool isIndoor) {}
void ZoneType::updateBlacksmithAmbience(float deltaTime) {}
void ZoneType::updateWeatherAmbience(float deltaTime, bool isIndoor) {}
void ZoneType::updateWaterAmbience(float deltaTime, bool isSwimming) {}
void ZoneType::updateZoneAmbience(float deltaTime, bool isIndoor) {}
void ZoneType::updateCityAmbience(float deltaTime) {}
void ZoneType::updateBellTolls(float deltaTime) {}
bool ZoneType::loadSound(const std::string& path, AmbientSample& sample, pipeline::AssetManager* assets) { return false; }
// --- CityType ---
bool CityType::initialize(pipeline::AssetManager* assets) { return false; }
void CityType::shutdown() {}
void CityType::update(float deltaTime, const glm::vec3& cameraPos, bool isIndoor, bool isSwimming = false, bool isBlacksmith = false) {}
void CityType::setWeather(WeatherType type) {}
void CityType::setZoneType(ZoneType type) {}
void CityType::setZoneId(uint32_t zoneId) {}
void CityType::setCityType(CityType type) {}
uint64_t CityType::addEmitter(const glm::vec3& position, AmbientType type) { return 0; }
void CityType::removeEmitter(uint64_t id) {}
void CityType::clearEmitters() {}
void CityType::setGameTime(float hours) {}
void CityType::setVolumeScale(float scale) {}
void CityType::updatePositionalEmitters(float deltaTime, const glm::vec3& cameraPos) {}
void CityType::updatePeriodicSounds(float deltaTime, bool isIndoor, bool isSwimming) {}
void CityType::updateWindAmbience(float deltaTime, bool isIndoor) {}
void CityType::updateBlacksmithAmbience(float deltaTime) {}
void CityType::updateWeatherAmbience(float deltaTime, bool isIndoor) {}
void CityType::updateWaterAmbience(float deltaTime, bool isSwimming) {}
void CityType::updateZoneAmbience(float deltaTime, bool isIndoor) {}
void CityType::updateCityAmbience(float deltaTime) {}
void CityType::updateBellTolls(float deltaTime) {}
bool CityType::loadSound(const std::string& path, AmbientSample& sample, pipeline::AssetManager* assets) { return false; }
// --- AmbientType ---
bool AmbientType::initialize(pipeline::AssetManager* assets) { return false; }
void AmbientType::shutdown() {}
void AmbientType::update(float deltaTime, const glm::vec3& cameraPos, bool isIndoor, bool isSwimming = false, bool isBlacksmith = false) {}
void AmbientType::setWeather(WeatherType type) {}
void AmbientType::setZoneType(ZoneType type) {}
void AmbientType::setZoneId(uint32_t zoneId) {}
void AmbientType::setCityType(CityType type) {}
uint64_t AmbientType::addEmitter(const glm::vec3& position, AmbientType type) { return 0; }
void AmbientType::removeEmitter(uint64_t id) {}
void AmbientType::clearEmitters() {}
void AmbientType::setGameTime(float hours) {}
void AmbientType::setVolumeScale(float scale) {}
void AmbientType::updatePositionalEmitters(float deltaTime, const glm::vec3& cameraPos) {}
void AmbientType::updatePeriodicSounds(float deltaTime, bool isIndoor, bool isSwimming) {}
void AmbientType::updateWindAmbience(float deltaTime, bool isIndoor) {}
void AmbientType::updateBlacksmithAmbience(float deltaTime) {}
void AmbientType::updateWeatherAmbience(float deltaTime, bool isIndoor) {}
void AmbientType::updateWaterAmbience(float deltaTime, bool isSwimming) {}
void AmbientType::updateZoneAmbience(float deltaTime, bool isIndoor) {}
void AmbientType::updateCityAmbience(float deltaTime) {}
void AmbientType::updateBellTolls(float deltaTime) {}
bool AmbientType::loadSound(const std::string& path, AmbientSample& sample, pipeline::AssetManager* assets) { return false; }
// --- AssetManager ---
public: AssetManager::AudioCoordinator() { return {}; }
bool AssetManager::initialize() { return false; }
void AssetManager::initializeWithAssets(pipeline::AssetManager* assetManager) {}
void AssetManager::updateZoneAudio(const ZoneAudioContext& ctx) {}
void AssetManager::onOriginalSoundtrackDisabled(game::ZoneManager* zm) {}
private:
    void AssetManager::playZoneMusic(const std::string& music) { return {}; }
// --- ZoneManager ---
public: ZoneManager::AudioCoordinator() { return {}; }
bool ZoneManager::initialize() { return false; }
void ZoneManager::initializeWithAssets(pipeline::AssetManager* assetManager) {}
void ZoneManager::shutdown() {}
void ZoneManager::updateZoneAudio(const ZoneAudioContext& ctx) {}
void ZoneManager::onOriginalSoundtrackDisabled(game::ZoneManager* zm) {}
private:
    void ZoneManager::playZoneMusic(const std::string& music) { return {}; }
// --- MusicManager ---
public: MusicManager::AudioCoordinator() { return {}; }
bool MusicManager::initialize() { return false; }
void MusicManager::initializeWithAssets(pipeline::AssetManager* assetManager) {}
void MusicManager::shutdown() {}
void MusicManager::updateZoneAudio(const ZoneAudioContext& ctx) {}
void MusicManager::onOriginalSoundtrackDisabled(game::ZoneManager* zm) {}
private:
    void MusicManager::playZoneMusic(const std::string& music) { return {}; }
// --- FootstepManager ---
public: FootstepManager::AudioCoordinator() { return {}; }
bool FootstepManager::initialize() { return false; }
void FootstepManager::initializeWithAssets(pipeline::AssetManager* assetManager) {}
void FootstepManager::shutdown() {}
void FootstepManager::updateZoneAudio(const ZoneAudioContext& ctx) {}
void FootstepManager::onOriginalSoundtrackDisabled(game::ZoneManager* zm) {}
private:
    void FootstepManager::playZoneMusic(const std::string& music) { return {}; }
// --- ActivitySoundManager ---
public: ActivitySoundManager::AudioCoordinator() { return {}; }
bool ActivitySoundManager::initialize() { return false; }
void ActivitySoundManager::initializeWithAssets(pipeline::AssetManager* assetManager) {}
void ActivitySoundManager::updateZoneAudio(const ZoneAudioContext& ctx) {}
void ActivitySoundManager::onOriginalSoundtrackDisabled(game::ZoneManager* zm) {}
private:
    void ActivitySoundManager::playZoneMusic(const std::string& music) { return {}; }
// --- MountSoundManager ---
public: MountSoundManager::AudioCoordinator() { return {}; }
bool MountSoundManager::initialize() { return false; }
void MountSoundManager::initializeWithAssets(pipeline::AssetManager* assetManager) {}
void MountSoundManager::shutdown() {}
void MountSoundManager::updateZoneAudio(const ZoneAudioContext& ctx) {}
void MountSoundManager::onOriginalSoundtrackDisabled(game::ZoneManager* zm) {}
private:
    void MountSoundManager::playZoneMusic(const std::string& music) { return {}; }
// --- NpcVoiceManager ---
public: NpcVoiceManager::AudioCoordinator() { return {}; }
bool NpcVoiceManager::initialize() { return false; }
void NpcVoiceManager::initializeWithAssets(pipeline::AssetManager* assetManager) {}
void NpcVoiceManager::shutdown() {}
void NpcVoiceManager::updateZoneAudio(const ZoneAudioContext& ctx) {}
void NpcVoiceManager::onOriginalSoundtrackDisabled(game::ZoneManager* zm) {}
private:
    void NpcVoiceManager::playZoneMusic(const std::string& music) { return {}; }
// --- PlayerVoiceManager ---
public: PlayerVoiceManager::AudioCoordinator() { return {}; }
bool PlayerVoiceManager::initialize() { return false; }
void PlayerVoiceManager::initializeWithAssets(pipeline::AssetManager* assetManager) {}
void PlayerVoiceManager::shutdown() {}
void PlayerVoiceManager::updateZoneAudio(const ZoneAudioContext& ctx) {}
void PlayerVoiceManager::onOriginalSoundtrackDisabled(game::ZoneManager* zm) {}
private:
    void PlayerVoiceManager::playZoneMusic(const std::string& music) { return {}; }
// --- AmbientSoundManager ---
public: AmbientSoundManager::AudioCoordinator() { return {}; }
bool AmbientSoundManager::initialize() { return false; }
void AmbientSoundManager::initializeWithAssets(pipeline::AssetManager* assetManager) {}
void AmbientSoundManager::updateZoneAudio(const ZoneAudioContext& ctx) {}
void AmbientSoundManager::onOriginalSoundtrackDisabled(game::ZoneManager* zm) {}
private:
    void AmbientSoundManager::playZoneMusic(const std::string& music) { return {}; }
// --- UiSoundManager ---
public: UiSoundManager::AudioCoordinator() { return {}; }
bool UiSoundManager::initialize() { return false; }
void UiSoundManager::initializeWithAssets(pipeline::AssetManager* assetManager) {}
void UiSoundManager::shutdown() {}
void UiSoundManager::updateZoneAudio(const ZoneAudioContext& ctx) {}
void UiSoundManager::onOriginalSoundtrackDisabled(game::ZoneManager* zm) {}
private:
    void UiSoundManager::playZoneMusic(const std::string& music) { return {}; }
// --- CombatSoundManager ---
public: CombatSoundManager::AudioCoordinator() { return {}; }
bool CombatSoundManager::initialize() { return false; }
void CombatSoundManager::initializeWithAssets(pipeline::AssetManager* assetManager) {}
void CombatSoundManager::shutdown() {}
void CombatSoundManager::updateZoneAudio(const ZoneAudioContext& ctx) {}
void CombatSoundManager::onOriginalSoundtrackDisabled(game::ZoneManager* zm) {}
private:
    void CombatSoundManager::playZoneMusic(const std::string& music) { return {}; }
// --- SpellSoundManager ---
public: SpellSoundManager::AudioCoordinator() { return {}; }
bool SpellSoundManager::initialize() { return false; }
void SpellSoundManager::initializeWithAssets(pipeline::AssetManager* assetManager) {}
void SpellSoundManager::shutdown() {}
void SpellSoundManager::updateZoneAudio(const ZoneAudioContext& ctx) {}
void SpellSoundManager::onOriginalSoundtrackDisabled(game::ZoneManager* zm) {}
private:
    void SpellSoundManager::playZoneMusic(const std::string& music) { return {}; }
// --- MovementSoundManager ---
public: MovementSoundManager::AudioCoordinator() { return {}; }
bool MovementSoundManager::initialize() { return false; }
void MovementSoundManager::initializeWithAssets(pipeline::AssetManager* assetManager) {}
void MovementSoundManager::shutdown() {}
void MovementSoundManager::updateZoneAudio(const ZoneAudioContext& ctx) {}
void MovementSoundManager::onOriginalSoundtrackDisabled(game::ZoneManager* zm) {}
private:
    void MovementSoundManager::playZoneMusic(const std::string& music) { return {}; }
// --- AudioCoordinator ---
bool AudioCoordinator::initialize() { return false; }
void AudioCoordinator::initializeWithAssets(pipeline::AssetManager* assetManager) {}
void AudioCoordinator::shutdown() {}
void AudioCoordinator::updateZoneAudio(const ZoneAudioContext& ctx) {}
void AudioCoordinator::onOriginalSoundtrackDisabled(game::ZoneManager* zm) {}
private:
    void AudioCoordinator::playZoneMusic(const std::string& music) { return {}; }
// --- AssetManager ---
void AssetManager::playWeaponSwing(WeaponSize size, bool isCrit = false) {}
void AssetManager::playWeaponMiss(bool twoHanded = false) {}
void AssetManager::playImpact(WeaponSize weaponSize, ImpactType impactType, bool isCrit = false) {}
void AssetManager::playClap() {}
void AssetManager::playPlayerAttackGrunt(PlayerRace race) {}
void AssetManager::playPlayerWound(PlayerRace race, bool isCrit = false) {}
void AssetManager::playPlayerDeath(PlayerRace race) {}
bool AssetManager::loadSound(const std::string& path, CombatSample& sample, pipeline::AssetManager* assets) { return false; }
void AssetManager::playSound(const std::vector<CombatSample>& library, float volumeMultiplier = 1.0f) {}
void AssetManager::playRandomSound(const std::vector<CombatSample>& library, float volumeMultiplier = 1.0f) {}
// --- CombatSoundManager ---
bool CombatSoundManager::initialize(pipeline::AssetManager* assets) { return false; }
void CombatSoundManager::setVolumeScale(float scale) {}
void CombatSoundManager::playWeaponSwing(WeaponSize size, bool isCrit = false) {}
void CombatSoundManager::playWeaponMiss(bool twoHanded = false) {}
void CombatSoundManager::playImpact(WeaponSize weaponSize, ImpactType impactType, bool isCrit = false) {}
void CombatSoundManager::playClap() {}
void CombatSoundManager::playPlayerAttackGrunt(PlayerRace race) {}
void CombatSoundManager::playPlayerWound(PlayerRace race, bool isCrit = false) {}
void CombatSoundManager::playPlayerDeath(PlayerRace race) {}
bool CombatSoundManager::loadSound(const std::string& path, CombatSample& sample, pipeline::AssetManager* assets) { return false; }
void CombatSoundManager::playSound(const std::vector<CombatSample>& library, float volumeMultiplier = 1.0f) {}
void CombatSoundManager::playRandomSound(const std::vector<CombatSample>& library, float volumeMultiplier = 1.0f) {}
// --- WeaponSize ---
bool WeaponSize::initialize(pipeline::AssetManager* assets) { return false; }
void WeaponSize::shutdown() {}
void WeaponSize::setVolumeScale(float scale) {}
void WeaponSize::playWeaponSwing(WeaponSize size, bool isCrit = false) {}
void WeaponSize::playWeaponMiss(bool twoHanded = false) {}
void WeaponSize::playImpact(WeaponSize weaponSize, ImpactType impactType, bool isCrit = false) {}
void WeaponSize::playClap() {}
void WeaponSize::playPlayerAttackGrunt(PlayerRace race) {}
void WeaponSize::playPlayerWound(PlayerRace race, bool isCrit = false) {}
void WeaponSize::playPlayerDeath(PlayerRace race) {}
bool WeaponSize::loadSound(const std::string& path, CombatSample& sample, pipeline::AssetManager* assets) { return false; }
void WeaponSize::playSound(const std::vector<CombatSample>& library, float volumeMultiplier = 1.0f) {}
void WeaponSize::playRandomSound(const std::vector<CombatSample>& library, float volumeMultiplier = 1.0f) {}
// --- ImpactType ---
bool ImpactType::initialize(pipeline::AssetManager* assets) { return false; }
void ImpactType::shutdown() {}
void ImpactType::setVolumeScale(float scale) {}
void ImpactType::playWeaponSwing(WeaponSize size, bool isCrit = false) {}
void ImpactType::playWeaponMiss(bool twoHanded = false) {}
void ImpactType::playImpact(WeaponSize weaponSize, ImpactType impactType, bool isCrit = false) {}
void ImpactType::playClap() {}
void ImpactType::playPlayerAttackGrunt(PlayerRace race) {}
void ImpactType::playPlayerWound(PlayerRace race, bool isCrit = false) {}
void ImpactType::playPlayerDeath(PlayerRace race) {}
bool ImpactType::loadSound(const std::string& path, CombatSample& sample, pipeline::AssetManager* assets) { return false; }
void ImpactType::playSound(const std::vector<CombatSample>& library, float volumeMultiplier = 1.0f) {}
void ImpactType::playRandomSound(const std::vector<CombatSample>& library, float volumeMultiplier = 1.0f) {}
// --- PlayerRace ---
bool PlayerRace::initialize(pipeline::AssetManager* assets) { return false; }
void PlayerRace::shutdown() {}
void PlayerRace::setVolumeScale(float scale) {}
void PlayerRace::playWeaponSwing(WeaponSize size, bool isCrit = false) {}
void PlayerRace::playWeaponMiss(bool twoHanded = false) {}
void PlayerRace::playImpact(WeaponSize weaponSize, ImpactType impactType, bool isCrit = false) {}
void PlayerRace::playClap() {}
void PlayerRace::playPlayerAttackGrunt(PlayerRace race) {}
void PlayerRace::playPlayerWound(PlayerRace race, bool isCrit = false) {}
void PlayerRace::playPlayerDeath(PlayerRace race) {}
bool PlayerRace::loadSound(const std::string& path, CombatSample& sample, pipeline::AssetManager* assets) { return false; }
void PlayerRace::playSound(const std::vector<CombatSample>& library, float volumeMultiplier = 1.0f) {}
void PlayerRace::playRandomSound(const std::vector<CombatSample>& library, float volumeMultiplier = 1.0f) {}
// --- AssetManager ---
public: AssetManager::FootstepManager() { return {}; }
void AssetManager::playFootstep(FootstepSurface surface, bool sprinting) {}
void AssetManager::playMountFootstep(FootstepSurface surface, FootstepBank bank) {}
void AssetManager::preloadSurface(SurfaceSamples* bank, FootstepSurface surface,
                        const std::vector<std::string>& candidates, const char* bankName) {}
bool AssetManager::playRandomStep(FootstepSurface surface, FootstepBank bank,
                        float minInterval, float volumeMul) { return false; }
// --- FootstepSurface ---
public: FootstepSurface::FootstepManager() { return {}; }
bool FootstepSurface::initialize(pipeline::AssetManager* assets) { return false; }
void FootstepSurface::shutdown() {}
void FootstepSurface::update(float deltaTime) {}
void FootstepSurface::playFootstep(FootstepSurface surface, bool sprinting) {}
void FootstepSurface::playMountFootstep(FootstepSurface surface, FootstepBank bank) {}
void FootstepSurface::preloadSurface(SurfaceSamples* bank, FootstepSurface surface,
                        const std::vector<std::string>& candidates, const char* bankName) {}
bool FootstepSurface::playRandomStep(FootstepSurface surface, FootstepBank bank,
                        float minInterval, float volumeMul) { return false; }
// --- FootstepBank ---
public: FootstepBank::FootstepManager() { return {}; }
bool FootstepBank::initialize(pipeline::AssetManager* assets) { return false; }
void FootstepBank::shutdown() {}
void FootstepBank::update(float deltaTime) {}
void FootstepBank::playFootstep(FootstepSurface surface, bool sprinting) {}
void FootstepBank::playMountFootstep(FootstepSurface surface, FootstepBank bank) {}
void FootstepBank::preloadSurface(SurfaceSamples* bank, FootstepSurface surface,
                        const std::vector<std::string>& candidates, const char* bankName) {}
bool FootstepBank::playRandomStep(FootstepSurface surface, FootstepBank bank,
                        float minInterval, float volumeMul) { return false; }
// --- FootstepManager ---
bool FootstepManager::initialize(pipeline::AssetManager* assets) { return false; }
void FootstepManager::update(float deltaTime) {}
void FootstepManager::playFootstep(FootstepSurface surface, bool sprinting) {}
void FootstepManager::playMountFootstep(FootstepSurface surface, FootstepBank bank) {}
void FootstepManager::preloadSurface(SurfaceSamples* bank, FootstepSurface surface,
                        const std::vector<std::string>& candidates, const char* bankName) {}
bool FootstepManager::playRandomStep(FootstepSurface surface, FootstepBank bank,
                        float minInterval, float volumeMul) { return false; }
// --- AssetManager ---
public: AssetManager::MountSoundManager() { return {}; }
void AssetManager::onMount(uint32_t creatureDisplayId, bool isFlying, const std::string& modelPath = "") {}
void AssetManager::onDismount() {}
void AssetManager::setMoving(bool moving) {}
void AssetManager::setFlying(bool flying) {}
void AssetManager::setGrounded(bool grounded) {}
void AssetManager::playRearUpSound() {}
void AssetManager::playJumpSound() {}
void AssetManager::playLandSound() {}
void AssetManager::playIdleSound() {}
private:
    MountType AssetManager::detectMountType(uint32_t creatureDisplayId) const { return {}; }
MountFamily AssetManager::detectMountFamily(uint32_t creatureDisplayId) const { return {}; }
MountFamily AssetManager::detectMountFamilyFromPath(const std::string& modelPath) const { return {}; }
void AssetManager::updateMountSounds() {}
void AssetManager::stopAllMountSounds() {}
void AssetManager::loadMountSounds() {}
bool AssetManager::loadSound(const std::string& path, MountSample& sample) { return false; }
const FamilySounds& AssetManager::getCurrentFamilySounds() const { return {}; }
// --- MountType ---
public: MountType::MountSoundManager() { return {}; }
bool MountType::initialize(pipeline::AssetManager* assets) { return false; }
void MountType::shutdown() {}
void MountType::update(float deltaTime) {}
void MountType::onMount(uint32_t creatureDisplayId, bool isFlying, const std::string& modelPath = "") {}
void MountType::onDismount() {}
void MountType::setMoving(bool moving) {}
void MountType::setFlying(bool flying) {}
void MountType::setGrounded(bool grounded) {}
void MountType::playRearUpSound() {}
void MountType::playJumpSound() {}
void MountType::playLandSound() {}
void MountType::playIdleSound() {}
private:
    MountType MountType::detectMountType(uint32_t creatureDisplayId) const { return {}; }
MountFamily MountType::detectMountFamily(uint32_t creatureDisplayId) const { return {}; }
MountFamily MountType::detectMountFamilyFromPath(const std::string& modelPath) const { return {}; }
void MountType::updateMountSounds() {}
void MountType::stopAllMountSounds() {}
void MountType::loadMountSounds() {}
bool MountType::loadSound(const std::string& path, MountSample& sample) { return false; }
const FamilySounds& MountType::getCurrentFamilySounds() const { return {}; }
// --- MountFamily ---
public: MountFamily::MountSoundManager() { return {}; }
bool MountFamily::initialize(pipeline::AssetManager* assets) { return false; }
void MountFamily::shutdown() {}
void MountFamily::update(float deltaTime) {}
void MountFamily::onMount(uint32_t creatureDisplayId, bool isFlying, const std::string& modelPath = "") {}
void MountFamily::onDismount() {}
void MountFamily::setMoving(bool moving) {}
void MountFamily::setFlying(bool flying) {}
void MountFamily::setGrounded(bool grounded) {}
void MountFamily::playRearUpSound() {}
void MountFamily::playJumpSound() {}
void MountFamily::playLandSound() {}
void MountFamily::playIdleSound() {}
private:
    MountType MountFamily::detectMountType(uint32_t creatureDisplayId) const { return {}; }
MountFamily MountFamily::detectMountFamily(uint32_t creatureDisplayId) const { return {}; }
MountFamily MountFamily::detectMountFamilyFromPath(const std::string& modelPath) const { return {}; }
void MountFamily::updateMountSounds() {}
void MountFamily::stopAllMountSounds() {}
void MountFamily::loadMountSounds() {}
bool MountFamily::loadSound(const std::string& path, MountSample& sample) { return false; }
const FamilySounds& MountFamily::getCurrentFamilySounds() const { return {}; }
// --- MountSoundManager ---
bool MountSoundManager::initialize(pipeline::AssetManager* assets) { return false; }
void MountSoundManager::update(float deltaTime) {}
void MountSoundManager::onMount(uint32_t creatureDisplayId, bool isFlying, const std::string& modelPath = "") {}
void MountSoundManager::onDismount() {}
void MountSoundManager::setMoving(bool moving) {}
void MountSoundManager::setFlying(bool flying) {}
void MountSoundManager::setGrounded(bool grounded) {}
void MountSoundManager::playRearUpSound() {}
void MountSoundManager::playJumpSound() {}
void MountSoundManager::playLandSound() {}
void MountSoundManager::playIdleSound() {}
private:
    MountType MountSoundManager::detectMountType(uint32_t creatureDisplayId) const { return {}; }
MountFamily MountSoundManager::detectMountFamily(uint32_t creatureDisplayId) const { return {}; }
MountFamily MountSoundManager::detectMountFamilyFromPath(const std::string& modelPath) const { return {}; }
void MountSoundManager::updateMountSounds() {}
void MountSoundManager::stopAllMountSounds() {}
void MountSoundManager::loadMountSounds() {}
bool MountSoundManager::loadSound(const std::string& path, MountSample& sample) { return false; }
const FamilySounds& MountSoundManager::getCurrentFamilySounds() const { return {}; }
// --- AssetManager ---
void AssetManager::playEnterWater(CharacterSize size) {}
void AssetManager::playWaterFootstep(CharacterSize size) {}
void AssetManager::playJump(PlayerRace race) {}
void AssetManager::playLand(PlayerRace race) {}
bool AssetManager::loadSound(const std::string& path, MovementSample& sample, pipeline::AssetManager* assets) { return false; }
void AssetManager::playSound(const std::vector<MovementSample>& library, float volumeMultiplier = 1.0f) {}
void AssetManager::playRandomSound(const std::vector<MovementSample>& library, float volumeMultiplier = 1.0f) {}
// --- MovementSoundManager ---
bool MovementSoundManager::initialize(pipeline::AssetManager* assets) { return false; }
void MovementSoundManager::setVolumeScale(float scale) {}
void MovementSoundManager::playEnterWater(CharacterSize size) {}
void MovementSoundManager::playWaterFootstep(CharacterSize size) {}
void MovementSoundManager::playJump(PlayerRace race) {}
void MovementSoundManager::playLand(PlayerRace race) {}
bool MovementSoundManager::loadSound(const std::string& path, MovementSample& sample, pipeline::AssetManager* assets) { return false; }
void MovementSoundManager::playSound(const std::vector<MovementSample>& library, float volumeMultiplier = 1.0f) {}
void MovementSoundManager::playRandomSound(const std::vector<MovementSample>& library, float volumeMultiplier = 1.0f) {}
// --- CharacterSize ---
bool CharacterSize::initialize(pipeline::AssetManager* assets) { return false; }
void CharacterSize::shutdown() {}
void CharacterSize::setVolumeScale(float scale) {}
void CharacterSize::playEnterWater(CharacterSize size) {}
void CharacterSize::playWaterFootstep(CharacterSize size) {}
void CharacterSize::playJump(PlayerRace race) {}
void CharacterSize::playLand(PlayerRace race) {}
bool CharacterSize::loadSound(const std::string& path, MovementSample& sample, pipeline::AssetManager* assets) { return false; }
void CharacterSize::playSound(const std::vector<MovementSample>& library, float volumeMultiplier = 1.0f) {}
void CharacterSize::playRandomSound(const std::vector<MovementSample>& library, float volumeMultiplier = 1.0f) {}
// --- PlayerRace ---
void PlayerRace::playEnterWater(CharacterSize size) {}
void PlayerRace::playWaterFootstep(CharacterSize size) {}
void PlayerRace::playJump(PlayerRace race) {}
void PlayerRace::playLand(PlayerRace race) {}
bool PlayerRace::loadSound(const std::string& path, MovementSample& sample, pipeline::AssetManager* assets) { return false; }
void PlayerRace::playSound(const std::vector<MovementSample>& library, float volumeMultiplier = 1.0f) {}
void PlayerRace::playRandomSound(const std::vector<MovementSample>& library, float volumeMultiplier = 1.0f) {}
// --- AssetManager ---
public: AssetManager::MusicManager() { return {}; }
void AssetManager::stopMusic(float fadeMs = 2000.0f) {}
void AssetManager::crossfadeTo(const std::string& mpqPath, float fadeMs = 3000.0f) {}
void AssetManager::crossfadeToFile(const std::string& filePath, float fadeMs = 3000.0f) {}
void AssetManager::setVolume(int volume) {}
void AssetManager::setUnderwaterMode(bool underwater) {}
void AssetManager::preloadMusic(const std::string& mpqPath) {}
private:
    float AssetManager::effectiveMusicVolume() const { return {}; }
void AssetManager::cancelPendingFileLoad() {}
void AssetManager::pollPendingFileLoad() {}
// --- MusicManager ---
bool MusicManager::initialize(pipeline::AssetManager* assets) { return false; }
void MusicManager::stopMusic(float fadeMs = 2000.0f) {}
void MusicManager::crossfadeTo(const std::string& mpqPath, float fadeMs = 3000.0f) {}
void MusicManager::crossfadeToFile(const std::string& filePath, float fadeMs = 3000.0f) {}
void MusicManager::update(float deltaTime) {}
void MusicManager::setVolume(int volume) {}
void MusicManager::setUnderwaterMode(bool underwater) {}
void MusicManager::preloadMusic(const std::string& mpqPath) {}
private:
    float MusicManager::effectiveMusicVolume() const { return {}; }
void MusicManager::cancelPendingFileLoad() {}
void MusicManager::pollPendingFileLoad() {}
// --- AssetManager ---
public: AssetManager::NpcVoiceManager() { return {}; }
void AssetManager::playGreeting(uint64_t npcGuid, VoiceType voiceType, const glm::vec3& position) {}
void AssetManager::playFarewell(uint64_t npcGuid, VoiceType voiceType, const glm::vec3& position) {}
void AssetManager::playVendor(uint64_t npcGuid, VoiceType voiceType, const glm::vec3& position) {}
void AssetManager::playPissed(uint64_t npcGuid, VoiceType voiceType, const glm::vec3& position) {}
void AssetManager::playAggro(uint64_t npcGuid, uint32_t displayId, VoiceType voiceType,
                   const glm::vec3& position) {}
void AssetManager::playCombatAttack(uint64_t npcGuid, uint32_t displayId,
                          const glm::vec3& position) {}
void AssetManager::playFlee(uint64_t npcGuid, VoiceType voiceType, const glm::vec3& position) {}
void AssetManager::loadVoiceSounds() {}
void AssetManager::loadCreatureAggroSounds() {}
bool AssetManager::loadSound(const std::string& path, VoiceSample& sample) { return false; }
bool AssetManager::playSoundEntry(uint32_t soundId, const glm::vec3& position) { return false; }
void AssetManager::playSound(uint64_t npcGuid, VoiceType voiceType, SoundCategory category, const glm::vec3& position) {}
// --- VoiceType ---
public: VoiceType::NpcVoiceManager() { return {}; }
bool VoiceType::initialize(pipeline::AssetManager* assets) { return false; }
void VoiceType::shutdown() {}
void VoiceType::playGreeting(uint64_t npcGuid, VoiceType voiceType, const glm::vec3& position) {}
void VoiceType::playFarewell(uint64_t npcGuid, VoiceType voiceType, const glm::vec3& position) {}
void VoiceType::playVendor(uint64_t npcGuid, VoiceType voiceType, const glm::vec3& position) {}
void VoiceType::playPissed(uint64_t npcGuid, VoiceType voiceType, const glm::vec3& position) {}
void VoiceType::playAggro(uint64_t npcGuid, uint32_t displayId, VoiceType voiceType,
                   const glm::vec3& position) {}
void VoiceType::playCombatAttack(uint64_t npcGuid, uint32_t displayId,
                          const glm::vec3& position) {}
void VoiceType::playFlee(uint64_t npcGuid, VoiceType voiceType, const glm::vec3& position) {}
void VoiceType::loadVoiceSounds() {}
void VoiceType::loadCreatureAggroSounds() {}
bool VoiceType::loadSound(const std::string& path, VoiceSample& sample) { return false; }
bool VoiceType::playSoundEntry(uint32_t soundId, const glm::vec3& position) { return false; }
void VoiceType::playSound(uint64_t npcGuid, VoiceType voiceType, SoundCategory category, const glm::vec3& position) {}
// --- NpcVoiceManager ---
bool NpcVoiceManager::initialize(pipeline::AssetManager* assets) { return false; }
void NpcVoiceManager::playGreeting(uint64_t npcGuid, VoiceType voiceType, const glm::vec3& position) {}
void NpcVoiceManager::playFarewell(uint64_t npcGuid, VoiceType voiceType, const glm::vec3& position) {}
void NpcVoiceManager::playVendor(uint64_t npcGuid, VoiceType voiceType, const glm::vec3& position) {}
void NpcVoiceManager::playPissed(uint64_t npcGuid, VoiceType voiceType, const glm::vec3& position) {}
void NpcVoiceManager::playAggro(uint64_t npcGuid, uint32_t displayId, VoiceType voiceType,
                   const glm::vec3& position) {}
void NpcVoiceManager::playCombatAttack(uint64_t npcGuid, uint32_t displayId,
                          const glm::vec3& position) {}
void NpcVoiceManager::playFlee(uint64_t npcGuid, VoiceType voiceType, const glm::vec3& position) {}
void NpcVoiceManager::loadVoiceSounds() {}
void NpcVoiceManager::loadCreatureAggroSounds() {}
bool NpcVoiceManager::loadSound(const std::string& path, VoiceSample& sample) { return false; }
bool NpcVoiceManager::playSoundEntry(uint32_t soundId, const glm::vec3& position) { return false; }
void NpcVoiceManager::playSound(uint64_t npcGuid, VoiceType voiceType, SoundCategory category, const glm::vec3& position) {}
// --- SoundCategory ---
public: SoundCategory::NpcVoiceManager() { return {}; }
bool SoundCategory::initialize(pipeline::AssetManager* assets) { return false; }
void SoundCategory::shutdown() {}
void SoundCategory::playGreeting(uint64_t npcGuid, VoiceType voiceType, const glm::vec3& position) {}
void SoundCategory::playFarewell(uint64_t npcGuid, VoiceType voiceType, const glm::vec3& position) {}
void SoundCategory::playVendor(uint64_t npcGuid, VoiceType voiceType, const glm::vec3& position) {}
void SoundCategory::playPissed(uint64_t npcGuid, VoiceType voiceType, const glm::vec3& position) {}
void SoundCategory::playAggro(uint64_t npcGuid, uint32_t displayId, VoiceType voiceType,
                   const glm::vec3& position) {}
void SoundCategory::playCombatAttack(uint64_t npcGuid, uint32_t displayId,
                          const glm::vec3& position) {}
void SoundCategory::playFlee(uint64_t npcGuid, VoiceType voiceType, const glm::vec3& position) {}
void SoundCategory::loadVoiceSounds() {}
void SoundCategory::loadCreatureAggroSounds() {}
bool SoundCategory::loadSound(const std::string& path, VoiceSample& sample) { return false; }
bool SoundCategory::playSoundEntry(uint32_t soundId, const glm::vec3& position) { return false; }
void SoundCategory::playSound(uint64_t npcGuid, VoiceType voiceType, SoundCategory category, const glm::vec3& position) {}
// --- AssetManager ---
void AssetManager::playError(PlayerErrorSpeech type, uint8_t raceId, uint8_t gender) {}
void AssetManager::ensureLibrary(uint8_t raceId, uint8_t gender) {}
// --- PlayerErrorSpeech ---
bool PlayerErrorSpeech::initialize(pipeline::AssetManager* assets) { return false; }
void PlayerErrorSpeech::shutdown() {}
void PlayerErrorSpeech::setVolumeScale(float scale) {}
void PlayerErrorSpeech::playError(PlayerErrorSpeech type, uint8_t raceId, uint8_t gender) {}
void PlayerErrorSpeech::ensureLibrary(uint8_t raceId, uint8_t gender) {}
// --- PlayerVoiceManager ---
bool PlayerVoiceManager::initialize(pipeline::AssetManager* assets) { return false; }
void PlayerVoiceManager::setVolumeScale(float scale) {}
void PlayerVoiceManager::playError(PlayerErrorSpeech type, uint8_t raceId, uint8_t gender) {}
void PlayerVoiceManager::ensureLibrary(uint8_t raceId, uint8_t gender) {}
// --- AssetManager ---
void AssetManager::playPrecast(MagicSchool school, SpellPower power) {}
void AssetManager::stopPrecast() {}
void AssetManager::playCast(MagicSchool school) {}
void AssetManager::playImpact(MagicSchool school, SpellPower power) {}
void AssetManager::playFireball() {}
void AssetManager::playFrostbolt() {}
void AssetManager::playLightningBolt() {}
void AssetManager::playHeal() {}
void AssetManager::playShadowBolt() {}
bool AssetManager::loadSound(const std::string& path, SpellSample& sample, pipeline::AssetManager* assets) { return false; }
void AssetManager::playSound(const std::vector<SpellSample>& library, float volumeMultiplier = 1.0f) {}
void AssetManager::playRandomSound(const std::vector<SpellSample>& library, float volumeMultiplier = 1.0f) {}
// --- SpellSoundManager ---
bool SpellSoundManager::initialize(pipeline::AssetManager* assets) { return false; }
void SpellSoundManager::setVolumeScale(float scale) {}
void SpellSoundManager::playPrecast(MagicSchool school, SpellPower power) {}
void SpellSoundManager::stopPrecast() {}
void SpellSoundManager::playCast(MagicSchool school) {}
void SpellSoundManager::playImpact(MagicSchool school, SpellPower power) {}
void SpellSoundManager::playFireball() {}
void SpellSoundManager::playFrostbolt() {}
void SpellSoundManager::playLightningBolt() {}
void SpellSoundManager::playHeal() {}
void SpellSoundManager::playShadowBolt() {}
bool SpellSoundManager::loadSound(const std::string& path, SpellSample& sample, pipeline::AssetManager* assets) { return false; }
void SpellSoundManager::playSound(const std::vector<SpellSample>& library, float volumeMultiplier = 1.0f) {}
void SpellSoundManager::playRandomSound(const std::vector<SpellSample>& library, float volumeMultiplier = 1.0f) {}
// --- MagicSchool ---
bool MagicSchool::initialize(pipeline::AssetManager* assets) { return false; }
void MagicSchool::shutdown() {}
void MagicSchool::setVolumeScale(float scale) {}
void MagicSchool::playPrecast(MagicSchool school, SpellPower power) {}
void MagicSchool::stopPrecast() {}
void MagicSchool::playCast(MagicSchool school) {}
void MagicSchool::playImpact(MagicSchool school, SpellPower power) {}
void MagicSchool::playFireball() {}
void MagicSchool::playFrostbolt() {}
void MagicSchool::playLightningBolt() {}
void MagicSchool::playHeal() {}
void MagicSchool::playShadowBolt() {}
bool MagicSchool::loadSound(const std::string& path, SpellSample& sample, pipeline::AssetManager* assets) { return false; }
void MagicSchool::playSound(const std::vector<SpellSample>& library, float volumeMultiplier = 1.0f) {}
void MagicSchool::playRandomSound(const std::vector<SpellSample>& library, float volumeMultiplier = 1.0f) {}
// --- SpellPower ---
bool SpellPower::initialize(pipeline::AssetManager* assets) { return false; }
void SpellPower::shutdown() {}
void SpellPower::setVolumeScale(float scale) {}
void SpellPower::playPrecast(MagicSchool school, SpellPower power) {}
void SpellPower::stopPrecast() {}
void SpellPower::playCast(MagicSchool school) {}
void SpellPower::playImpact(MagicSchool school, SpellPower power) {}
void SpellPower::playFireball() {}
void SpellPower::playFrostbolt() {}
void SpellPower::playLightningBolt() {}
void SpellPower::playHeal() {}
void SpellPower::playShadowBolt() {}
bool SpellPower::loadSound(const std::string& path, SpellSample& sample, pipeline::AssetManager* assets) { return false; }
void SpellPower::playSound(const std::vector<SpellSample>& library, float volumeMultiplier = 1.0f) {}
void SpellPower::playRandomSound(const std::vector<SpellSample>& library, float volumeMultiplier = 1.0f) {}
// --- AssetManager ---
void AssetManager::playBagOpen() {}
void AssetManager::playBagClose() {}
void AssetManager::playQuestLogOpen() {}
void AssetManager::playQuestLogClose() {}
void AssetManager::playCharacterSheetOpen() {}
void AssetManager::playCharacterSheetClose() {}
void AssetManager::playAuctionHouseOpen() {}
void AssetManager::playAuctionHouseClose() {}
void AssetManager::playGuildBankOpen() {}
void AssetManager::playGuildBankClose() {}
void AssetManager::playButtonClick() {}
void AssetManager::playMenuButtonClick() {}
void AssetManager::playQuestActivate() {}
void AssetManager::playQuestComplete() {}
void AssetManager::playQuestFailed() {}
void AssetManager::playQuestUpdate() {}
void AssetManager::playFishingBite() {}
void AssetManager::playLootCoinSmall() {}
void AssetManager::playLootCoinLarge() {}
void AssetManager::playLootItem() {}
void AssetManager::playDropOnGround() {}
void AssetManager::playPickupBag() {}
void AssetManager::playPickupBook() {}
void AssetManager::playPickupCloth() {}
void AssetManager::playPickupFood() {}
void AssetManager::playPickupGem() {}
void AssetManager::playEating() {}
void AssetManager::playDrinking() {}
void AssetManager::playLevelUp() {}
void AssetManager::playAchievementAlert() {}
void AssetManager::playError() {}
void AssetManager::playTargetSelect() {}
void AssetManager::playTargetDeselect() {}
void AssetManager::playWhisperReceived() {}
void AssetManager::playMailReceived() {}
void AssetManager::playMinimapPing() {}
bool AssetManager::loadSound(const std::string& path, UISample& sample, pipeline::AssetManager* assets) { return false; }
void AssetManager::playSound(const std::vector<UISample>& library) {}
// --- UiSoundManager ---
bool UiSoundManager::initialize(pipeline::AssetManager* assets) { return false; }
void UiSoundManager::setVolumeScale(float scale) {}
void UiSoundManager::playBagOpen() {}
void UiSoundManager::playBagClose() {}
void UiSoundManager::playQuestLogOpen() {}
void UiSoundManager::playQuestLogClose() {}
void UiSoundManager::playCharacterSheetOpen() {}
void UiSoundManager::playCharacterSheetClose() {}
void UiSoundManager::playAuctionHouseOpen() {}
void UiSoundManager::playAuctionHouseClose() {}
void UiSoundManager::playGuildBankOpen() {}
void UiSoundManager::playGuildBankClose() {}
void UiSoundManager::playButtonClick() {}
void UiSoundManager::playMenuButtonClick() {}
void UiSoundManager::playQuestActivate() {}
void UiSoundManager::playQuestComplete() {}
void UiSoundManager::playQuestFailed() {}
void UiSoundManager::playQuestUpdate() {}
void UiSoundManager::playFishingBite() {}
void UiSoundManager::playLootCoinSmall() {}
void UiSoundManager::playLootCoinLarge() {}
void UiSoundManager::playLootItem() {}
void UiSoundManager::playDropOnGround() {}
void UiSoundManager::playPickupBag() {}
void UiSoundManager::playPickupBook() {}
void UiSoundManager::playPickupCloth() {}
void UiSoundManager::playPickupFood() {}
void UiSoundManager::playPickupGem() {}
void UiSoundManager::playEating() {}
void UiSoundManager::playDrinking() {}
void UiSoundManager::playLevelUp() {}
void UiSoundManager::playAchievementAlert() {}
void UiSoundManager::playError() {}
void UiSoundManager::playTargetSelect() {}
void UiSoundManager::playTargetDeselect() {}
void UiSoundManager::playWhisperReceived() {}
void UiSoundManager::playMailReceived() {}
void UiSoundManager::playMinimapPing() {}
bool UiSoundManager::loadSound(const std::string& path, UISample& sample, pipeline::AssetManager* assets) { return false; }
void UiSoundManager::playSound(const std::vector<UISample>& library) {}

} // namespace wowee::audio